import React from 'react';
import Head from 'next/head';
import CrewPage from '../src/Components/Pages/CrewPage';

const Crew = () => {
  return (
    <>
      <Head>
        <title>Space Tourism Agency | Crew</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <CrewPage />
    </>
  );
};

export default Crew;
