import Head from 'next/head';
import React from 'react';

//Components
import DestinationsPage from '../src/Components/Pages/DestinationsPage';

const Destinations = () => {
  return (
    <>
      <Head>
        <title>Space Tourism Agency | Destinations</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <DestinationsPage />
    </>
  );
};

export default Destinations;
