import Head from 'next/head';
import HomePage from '../src/Components/Pages/HomePage';

export default function Home() {
  return (
    <main>
      <Head>
        <title>Space Tourism Agency</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HomePage />
    </main>
  );
}
