import React from 'react';
import Head from 'next/head';
import TechnologyPage from '../src/Components/Pages/TechnologyPage';

const Technology = () => {
  return (
    <>
      <Head>
        <title>Space Tourism Agency | Technology</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <TechnologyPage />
    </>
  );
};

export default Technology;
